%macro pager_init(memname=);
	options mprint mlogic;
	%global tablename pagenum fobs lobs curpage totpagenum save_tablename;
	/*
	data _null_;
		if libref('save') then do;
			%put NOTE: Session Created!!!;
			rc=stpsrv_session('create');
			rc=stpsrvset('session timeout',60*60*24);
		end;
	run;	
	data _null_;
		length
			cmd $1024.
		;
		file _webout;
		save_path=pathname('save');
		save_path=TRANSLATE(save_path,"/","\");
		put '<script>';
		cmd='nstp_sessionid="'||"&_SESSIONID"||'" ;';
		put cmd;
		cmd='save_path="'||strip(save_path)||'" ;';
		put cmd;
		put '</script>';
	run;  	
	*/
	options mprint mlogic source source2 notes;
	data _null_;
		work_path=pathname("work");
		save_path=symget("save_path");
		fileexist=fileexist(save_path);
		call symput("fileexist",fileexist);
		call symput("save_path",trim(save_path));
		call symput("work_path",trim(work_path));
	run;
	%put NOTE: save_path = &save_path;
	%put NOTE: fileexist = &fileexist;
	
	%if &fileexist > 0 %then %do;
		libname _save "&save_path";
	%end;
	%else %do;
		libname _save "&work_path";
	%end;
	options nomprint nomlogic nosource nosource2 nonotes;
	
	%let tblname=%sysfunc(reverse(%sysfunc(scan(%sysfunc(reverse(&memname)),1,.))));
	%let tablename=_save.&tblname;
	%let save_tablename=&tablename;
	
	%if &pagenum = %then %do;
		data &tablename;
			set &memname ;
		run;
	%end;
	%else %do;
		*libname save "&_SAVEPATH";
	%end;
	%put NOTE: tablename : &tablename;
	%let dsid=%sysfunc(open(&tablename));
	%if &dsid > 0 %then %do;
		%let obsnum=%sysfunc(attrn(&dsid,nobs));
		%put NOTE: OBS Num : &obsnum ;
	%end;
	%else %put ERROR: Data cannot open!!!;
	%if &dsid > 0 %then %let rc=%sysfunc(close(&dsid));	
	%let totpagenum=%sysfunc(ceil(&obsnum/&_STPREPORT_PAGE));
	%if &pagenum = %then %do;
		%let pagenum=1;
		%let fobs=1;
		%let lobs=&_STPREPORT_PAGE;
		%let curpage=1;
	%end;
	%else %do;
		%let fobs=%eval((&pagenum-1)*&_STPREPORT_PAGE+1);
		%let lobs=%eval(&_STPREPORT_PAGE*(&pagenum));
		%let curpage=%eval(&pagenum);
		%if &fobs > &obsnum %then %do;
			%let fobs=&obsnum;
			%let lobs=max;
			%let curpage=&totpagenum;
		%end;
	%end;
	options firstobs=&fobs obs=&lobs ;
	ods _all_ close;	
%mend;

%macro pager_main;
data _null_;
	length link pg $5000;
	file _webout;
	put "<div class=branch><div class=dvPagePanel style=''>";
	lpg=mod(&totpagenum,10); 
	left="<img src='/SASHBI/images/arrow-left-default.gif' border=0>";
	left_end="<span style='width:30px;padding:0px 5px 0px 5px;'><a href='javascript:goPage("||'"1'||'"'||");'><img src='/SASHBI/images/arrow-left-end-default.gif' border=0></a></span>";
	right="<img src='/SASHBI/images/arrow-right-default.gif' border=0>";
	right_end="<span style='width:30px;padding:0px 5px 0px 5px;'><a href='javascript:goPage("||'"'||"&totpagenum"||'"'||");'><img src='/SASHBI/images/arrow-right-end-default.gif' border=0></a></span>";
	if mod(&curpage,10) eq 0 then spg=int((&curpage-1)/10)*10+1;
    else spg=int(&curpage/10)*10+1;
	if spg+10 > &totpagenum then epg=&totpagenum;
	else epg=spg+9;
	*link="<a href='&_url?"||'_debug=log&_program='||"&_program"||'&tablename='||"&tablename"||'&pagesize='||"&pagesize"||'&page=';
	link="<span style='width:30px;padding:0px 5px 0px 5px;'><a href='javascript:goPage("||'"';
	if spg > 10 then do;
		pg=left_end||trim(link)||trim(left(spg-1))||'");'||"'>"||left||"</a></span>";
		put pg;
	end;
	do ii=spg to epg;
		if &curpage eq ii then pg="<span style='width:30px;padding:0px 5px 0px 5px;'>"||trim(left(ii))||"</span>";
		else pg=trim(link)||trim(left(ii))||'");'||"'>"||trim(left(ii))||'</a></span>';
		put pg;
	end;
	if epg < &totpagenum  then do;
		pg=trim(link)||trim(left(ii))||'");'||"'>"||right||"</a></span>"||right_end;
		put pg;
	end;
	put "</div>";
	put '<script>';
	cmd='stp_sessionid="'||"&_SESSIONID"||'" ;';
	put cmd;
	put '</script>';
	put "</div>";
run;

options firstobs=1 obs=max;
%mend;
