filename _temp "%trim(&path)\_&uid.json";
PROC SUMMARY DATA=_LAST_ NWAY MISSING;
	CLASS &_grpX;
	VAR &_grpY;
	OUTPUT OUT=WORK.TARGET_&UID SUM=;
RUN;	
DATA WORK.TARGET_&UID;
	SET _LAST_;
	label=&_grpX;
	value=&_grpY;
	KEEP label value;
RUN;
PROC JSON OUT=_temp PRETTY; 
	WRITE OPEN ARRAY;
		WRITE OPEN OBJECT; 
			WRITE VALUES key "Cumulative Return";
			WRITE VALUES "values";
			WRITE OPEN ARRAY;
				EXPORT WORK.TARGET_&UID /  NOSASTAGS  ;
			WRITE CLOSE;
		WRITE CLOSE;
	WRITE CLOSE;
RUN;
data _null_;
		infile _temp length=len encoding="utf-8";
		file webout;
		input json $varying200. len;
		put json;
run;			
