filename _temp "%trim(&path)\_&uid.json";
PROC SUMMARY DATA=_LAST_ NWAY MISSING;
	CLASS &_grpX;
	VAR &_grpY;
	OUTPUT OUT=WORK.TARGET_&UID SUM=;
RUN;	
DATA WORK.TARGET_&UID;
	SET _LAST_;
	key=&_grpX;
	y=&_grpY;
	KEEP key y;
RUN;
PROC JSON OUT=_temp pretty ;
   EXPORT WORK.TARGET_&UID / NOSASTAGS  ;
RUN;
data _null_;
		infile _temp length=len encoding="utf-8";
		file webout;
		input json $varying200. len;
		put json;
run;			
