%stpbegin;
	TITLE H=6 "&COUNTRY / &PRODTYPE / &PRODUCT";
	PROC TABULATE
		DATA=HBIDEMO.PRDSALE;
		VAR PREDICT  /style=[WIDTH=50px];;
		VAR ACTUAL   /style=[WIDTH=100px];;
		CLASS YEAR QUARTER MONTH;
		CLASS PRODUCT			/	ORDER=UNFORMATTED MISSING;
		CLASS PRODTYPE		/	ORDER=UNFORMATTED MISSING;
		CLASS COUNTRY			/	ORDER=UNFORMATTED MISSING;
		CLASS REGION 			/	ORDER=UNFORMATTED MISSING;
		CLASSLEV YEAR			/ style=[WIDTH=50px TEXTALIGN=CENTER];
		CLASSLEV QUARTER	/ style=[WIDTH=100px TEXTALIGN=CENTER];
		CLASSLEV MONTH		/ style=[WIDTH=150px TEXTALIGN=CENTER];
		CLASSLEV COUNTRY	/ style=[TEXTALIGN=CENTER];
		
		TABLE 
			YEAR=''*QUARTER=''*MONTH='',
			COUNTRY=''* (PREDICT='Predict Amount' ACTUAL='Actual Amount')*SUM=''*F=COMMA20.
		;
	RUN;
%stpend;
