
ods html file=_webout (no_top_matter no_bottom_matter) path=&_tmpcat(url=&_replay) ;*STYLE=HtmlBlue;
	goptions reset=all;
	goptions XPIXELS=400 YPIXELS=250 dev=actximg; *dev=actximg activex;
	Axis1
		STYLE=1
		WIDTH=1
		MINOR=NONE;
	Axis2
		STYLE=1
		WIDTH=1;
	Legend1
		FRAME
		CBORDER=CX003366
		CFRAME=WHITE
		POSITION = (MIDDLE RIGHT OUTSIDE)
		LABEL=( FONT='Arial' HEIGHT=9pt COLOR=GREEN   "Legend")
		;	
	PROC GCHART DATA =HBIDEMO.PRDSALE;
		PIE	 COUNTRY /
			SUMVAR=ACTUAL
			TYPE=SUM
			LEGEND=LEGEND1
			SLICE=ARROW
			PERCENT=INSIDE
			VALUE=OUTSIDE
			OTHER=4
			OTHERLABEL="etc."
			COUTLINE=BLACK
			NOHEADING
	;
	RUN; QUIT;	
	PROC GCHART DATA=HBIDEMO.PRDSALE;
		VBAR COUNTRY /
		SUMVAR=ACTUAL
		CLIPREF
		FRAME	TYPE=SUM
		NOLEGEND
		COUTLINE=BLACK
		RAXIS=AXIS1
		MAXIS=AXIS2
		PATTERNID=MIDPOINT
	;
	RUN; QUIT;
	
	PROC TABULATE
	DATA=SASHELP.PRDSALE;
		VAR PREDICT  /style=[WIDTH=50px];;
		VAR ACTUAL   /style=[WIDTH=100px];;
		CLASS YEAR QUARTER MONTH;
		CLASS PRODUCT		/	ORDER=UNFORMATTED MISSING;
		CLASS PRODTYPE		/	ORDER=UNFORMATTED MISSING;
		CLASS COUNTRY		/	ORDER=UNFORMATTED MISSING;
		CLASS REGION 		/	ORDER=UNFORMATTED MISSING;
		CLASSLEV YEAR		/ style=[WIDTH=50px TEXTALIGN=CENTER];
		CLASSLEV QUARTER	/ style=[WIDTH=40px TEXTALIGN=CENTER];
		CLASSLEV MONTH		/ style=[WIDTH=50px TEXTALIGN=CENTER];
		CLASSLEV COUNTRY	/ style=[TEXTALIGN=CENTER];
		
		TABLE 
			YEAR=''*QUARTER=''*MONTH='',	
			COUNTRY=''* (PREDICT='Predict' ACTUAL='Actual' PREDICT='Predict' ACTUAL='Actual')*SUM=''*F=COMMA20.
		;
	RUN;
ods html close;
