/* %inc "C:\SASHBI\Macro\hbi_init.sas"; */


PROC SUMMARY DATA=HBIDEMO.BUCKET_14 MISSING NWAY;
	CLASS LV1 BUCKET_NO;
	VAR MAT_CAP MAT_INT REP_CAP REP_INT;
	OUTPUT OUT=BK SUM=;
RUN;
PROC SORT DATA=WORK.BK; BY LV1 BUCKET_NO;;
PROC TRANSPOSE DATA=WORK.BK OUT=WORK.BK_TRAN;
	VAR MAT_CAP MAT_INT REP_CAP REP_INT;
	BY LV1 BUCKET_NO;;
RUN;
PROC SORT DATA=WORK.BK_TRAN NODUPKEY OUT=UNIQ_CLASS;
	BY LV1 _NAME_;
RUN;

DATA WORK.GRAPH;
	SET WORK.BK_TRAN;
	y=COL1/1;
	x=bucket_no;
	anal_var=_name_;
	KEEP LV1 _NAME_ x y anal_var;
RUN;	


%JSON4BAR(
	DATA						=WORK.GRAPH,
	CLASS_INFO			=WORK.UNIQ_CLASS,
	CLASS_VAR_NAME1	=LV1,
	CLASS_VAR_NAME2	=_NAME_,
	CLASS_VAR_LABEL	=_LABEL_
);
                       
