%inc "C:\SASHBI\Macro\hbi_init.sas";


PROC SQL;
	CREATE TABLE WORK.CURRENCY_RATE AS
	SELECT * FROM HBIDEMO.CURRENCY_RATE
	WHERE BASE_DT BETWEEN INPUT("&BASE_DT_START",YYMMDD10.) AND INPUT("&BASE_DT_END",YYMMDD10.)
		AND CURRENCY_NAME = "&CURRENCY_NAME"
	;
QUIT;
DATA WORK.PLOT;
	SET CURRENCY_RATE;
		GRP_ID="Interest Rate";
	  X=BASE_DT*24*60*60*1000 - (365*10*24*60*60*1000) - (3*24*60*60*1000);
	  Y=CURRENCY_RATE;
	  KEEP GRP_ID X Y;
RUN;



%JSON4LINE(
	DATA=WORK.PLOT,
	LINE_VAR=GRP_ID		
);
                       
