%inc "C:\SASHBI\Macro\hbi_init.sas";

%let ANAL_VAR=ACTUAL;
PROC SUMMARY DATA=HBIDEMO.PRDSALE MISSING NWAY;
	CLASS PRODUCT;
	VAR &ANAL_VAR ;
	OUTPUT OUT=PRODUCT SUM=;
	FORMAT &ANAL_VAR COMMA10.;
RUN;

DATA WORK.GRAPH;
	SET WORK.PRODUCT;*(WHERE=(_NAME_="&ANAL_VAR"));
	key=PRODUCT;
	y=&ANAL_VAR;
	KEEP key y;
RUN;	

PROC JSON OUT=_webout pretty  nosastags;
   EXPORT WORK.GRAPH;
RUN;
