%inc "C:\SASHBI\Macro\hbi_init.sas";

%let ANAL_VAR	=ACTUAL;
%LET CLS_VAR	=PRODUCT;
%MACRO GET_DATA;

		DATA WORK.PRDSALE;
			SET HBIDEMO.PRDSALE;
		RUN;

		
%MEND GET_DATA;
%GET_DATA;

	PROC SUMMARY DATA=WORK.PRDSALE MISSING NWAY;
		CLASS &CLS_VAR;
		VAR &ANAL_VAR ;
		OUTPUT OUT=&CLS_VAR SUM=;
		FORMAT &ANAL_VAR COMMA10.;
	RUN;
	DATA WORK.BARCHART;
		SET WORK.&CLS_VAR;
		label=&CLS_VAR;
		value=INT(RANUNI(0)*100000);*&ANAL_VAR;
		KEEP label value;
	RUN;
	PROC JSON OUT=_webout PRETTY; 
		WRITE OPEN ARRAY;

			WRITE OPEN OBJECT; 
				WRITE VALUES key "Cumulative Return";
				WRITE VALUES "values";
				WRITE OPEN ARRAY;
					EXPORT WORK.BARCHART /  NOSASTAGS  ;
				WRITE CLOSE;
			WRITE CLOSE;
				
		WRITE CLOSE;
	RUN;
