%inc "C:\SASHBI\Macro\hbi_init.sas";

%let ANAL_VAR	=ACTUAL;
%LET CLS_VAR	=PRODUCT;
%MACRO GET_DATA;
	%IF &YEAR = ALL %THEN %DO;
		DATA WORK.PRDSALE;
			SET HBIDEMO.PRDSALE;
		%IF &COUNTRY =  %THEN %DO;
		%END;
		%ELSE %DO;
			WHERE COUNTRY="&COUNTRY";
		%END;			
		RUN;
	%END;
	%ELSE %DO;
		DATA WORK.PRDSALE(WHERE=(YEAR=&YEAR));
			SET HBIDEMO.PRDSALE;
		%IF &COUNTRY =  %THEN %DO;
		%END;
		%ELSE %DO;
			WHERE COUNTRY="&COUNTRY";
		%END;			
		RUN;
	%END;
	/*
	%IF %SYMEXIST(COUNTRY) %THEN %DO;
	DATA WORK.PRDSALE;
		SET WORK.PRDSALE(WHERE=(COUNTRY="&PARAM1"));
	RUN;
	%END;
	*/
		
%MEND GET_DATA;
%GET_DATA;

	PROC SUMMARY DATA=WORK.PRDSALE MISSING NWAY;
		CLASS &CLS_VAR;
		VAR &ANAL_VAR ;
		OUTPUT OUT=&CLS_VAR SUM=;
		FORMAT &ANAL_VAR COMMA10.;
	RUN;
	DATA WORK.BARCHART;
		SET WORK.&CLS_VAR;
		label=&CLS_VAR;
		value=&ANAL_VAR;
		KEEP label value;
	RUN;
	PROC JSON OUT=_webout PRETTY; 
		WRITE OPEN ARRAY;

			WRITE OPEN OBJECT; 
				WRITE VALUES key "Cumulative Return";
				WRITE VALUES "values";
				WRITE OPEN ARRAY;
					EXPORT WORK.BARCHART /  NOSASTAGS  ;
				WRITE CLOSE;
			WRITE CLOSE;
				
		WRITE CLOSE;
	RUN;
