%inc "C:\SASHBI\Macro\hbi_init.sas";

%GLOBAL ANAL_VAR;
		%let ANAL_VAR=ACTUAL;
%MACRO GET_PARAM;
	%IF &YEAR =ALL %THEN %DO;
		PROC SUMMARY DATA=HBIDEMO.PRDSALE MISSING NWAY;
			CLASS COUNTRY;
			VAR &ANAL_VAR ;
			OUTPUT OUT=COUNTRY SUM=;
			FORMAT &ANAL_VAR COMMA10.;
		RUN;
	%END;
	%ELSE %DO;
		PROC SUMMARY DATA=HBIDEMO.PRDSALE(WHERE=(YEAR=&YEAR)) MISSING NWAY;
			CLASS COUNTRY;
			VAR &ANAL_VAR ;
			OUTPUT OUT=COUNTRY SUM=;
			FORMAT &ANAL_VAR COMMA10.;
		RUN;		
	%END;
%MEND;
%GET_PARAM;



DATA WORK.GRAPH;
	SET WORK.COUNTRY;
	key=COUNTRY;
	y=&ANAL_VAR;
	KEEP key y;
RUN;	

PROC JSON OUT=_webout pretty  nosastags;
   EXPORT WORK.GRAPH;
RUN;
