%inc "C:\SASHBI\Macro\hbi_init.sas";

%GLOBAL ANAL_VAR;
		%let ANAL_VAR=ACTUAL;
%MACRO GET_PARAM;
		PROC SUMMARY DATA=HBIDEMO.PRDSALE MISSING NWAY;
			CLASS COUNTRY;
			VAR &ANAL_VAR ;
			OUTPUT OUT=COUNTRY SUM=;
			FORMAT &ANAL_VAR COMMA10.;
		RUN;

%MEND;
%GET_PARAM;



DATA WORK.GRAPH;
	SET WORK.COUNTRY;
	key=COUNTRY;
	y=INT(RANUNI(0)*1000);*&ANAL_VAR;
	KEEP key y;
RUN;	

PROC JSON OUT=_webout pretty  nosastags;
   EXPORT WORK.GRAPH;
RUN;
