%inc "C:\SASHBI\Macro\hbi_init.sas";




%MACRO GET_DATA;
	%IF &YEAR = ALL %THEN %DO;
		DATA WORK.PRDSALE;
			LENGTH OBS 8 COUNTRY REGION DIVISION PRODTYPE PRODUCT $20 YEAR QUARTER MONTH ACTUAL PREDICT 8;
			SET HBIDEMO.PRDSALE;
		%IF &COUNTRY =  %THEN %DO;
		%END;
		%ELSE %DO;
			WHERE COUNTRY="&COUNTRY";
		%END;		
	%END;
	%ELSE %DO;
		DATA WORK.PRDSALE(WHERE=(YEAR=&YEAR));
			LENGTH OBS 8 COUNTRY REGION DIVISION PRODTYPE PRODUCT $20 YEAR QUARTER MONTH ACTUAL PREDICT 8;
			SET HBIDEMO.PRDSALE;
		%IF &COUNTRY =  %THEN %DO;
		%END;
		%ELSE %DO;
			WHERE COUNTRY="&COUNTRY";
		%END;			
	%END;
	%IF &PRODUCT =  %THEN %DO;
	%END;
	%ELSE %DO;
			WHERE ALSO PRODUCT="&PRODUCT";		
	%END;
			OBS=_N_;
			LABEL OBS = 'OBS';
		RUN;


%MEND GET_DATA;
%GET_DATA;
PROC SUMMARY DATA=WORK.PRDSALE NWAY MISSING;
	CLASS YEAR COUNTRY PRODTYPE PRODUCT;
	VAR ACTUAL PREDICT;
	OUTPUT OUT=WORK.PRDSALE2 SUM=;
RUN;	


%json4Slick(
	tableName=work.prdsale2,
	columns	=%str(YEAR COUNTRY PRODTYPE PRODUCT ACTUAL PREDICT),
	width	=%str(90 90 90 90 90 90 90 90 90 120 120), 
	css		=%str(c c l l l l l l l r r),
	sort	=%str(1 1 1 1 1 1 1 1 1 1 1),
	resize	=%str(1 1 1 1 1 1 1 1 1 0 0),
	enableCellNavigation=true, 
	enableColumnReorder=false, 
	multiColumnSort=true);
/*
*/
